# Generated by Django 4.0.6 on 2022-07-25 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=255)),
                ('post_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_content', models.TextField()),
                ('post_excerpt', models.TextField()),
                ('post_img', models.ImageField(blank=True, null=True, upload_to='post_img/%Y/%m/%d')),
                ('post_published', models.BooleanField(default=False)),
                ('post_autor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('post_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.category')),
            ],
        ),
    ]
